services:
  - type: web
    name: pixel-positions-1
    runtime: php
    buildCommand: |
      sudo add-apt-repository ppa:ondrej/php -y
      sudo apt-get update
      sudo apt-get install -y php8.2 php8.2-cli php8.2-mbstring php8.2-xml php8.2-zip php8.2-mysql
      curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      composer install --no-dev --optimize-autoloader
      php artisan optimize
    startCommand: php artisan serve --host=0.0.0.0 --port=${PORT}
